
name: Sensor Mega

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v2
      - name: Install Arduino AVR Core (for Mega)
        shell: bash  # Use Git Bash for consistent CLI syntax
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
          arduino-cli lib install oneWire
          arduino-cli lib install SD
          arduino-cli lib install RTClib
          arduino-cli lib install DallasTemperature
          arduino-cli lib install DHTlib
          arduino-cli lib install ArduinoJson
          #arduino-cli config dump
      - name: Compile Sketch for Arduino Mega
        shell: bash
        run: |
          arduino-cli compile --fqbn arduino:avr:mega --build-path ./build ./task-sens
          ls ./task-sens
          ls ./build
      - name: Archive code task-sens-elf
        uses: actions/upload-artifact@v4
        with:
          name: task-sens-elf
          path: ./build/task-sens.ino.elf
      - name: Archive code task-sens-hex
        uses: actions/upload-artifact@v4
        with:
          name: task-sens-hex
          path: ./build/task-sens.ino.hex
